# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    secret_key_base: f98af8447cee71f57708489780665230bb882ef57314e6e27bf529be67011355f5f6d8f5b716af50c631caad103c2881c97f628d1770454431305ae1bad7688a

test:
    secret_key_base: 534b6a6b2a791c9fd9c273dbc2767fb1ac8edb64d327959c862a0a26e79d939210e5a85581ca56e745963f26ebad2af8915007d2cbf0cbd902d8f10d5fe76480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
